import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const read = (name: string) => readFileSync(fileURLToPath(new URL(name, import.meta.url)), 'utf8')
const browserSource = read('./BrowserWorkspace.tsx')
const navSource = read('./AgentNav.tsx')
const shellSource = read('./AgentShell.tsx')
const conversationSource = read('./AgentConversation.tsx')

describe('local browser workspace contract', () => {
  it('lives in the right workbench instead of the primary navigation or center page', () => {
    expect(navSource).not.toContain('data-agent-nav="browser"')
    expect(shellSource).toContain('data-workbench-empty')
    expect(shellSource).toContain('className={styles.workbenchEmptyActions}')
    expect(shellSource).toContain('onClick={() => openWorkbenchTab(tool.id)}')
    expect(shellSource).toContain('data-workbench-empty-action={tool.id}')
    expect(shellSource).toContain('data-workbench-add')
    expect(shellSource).toContain('data-workbench-add-option={tool.id}')
    expect(shellSource).toContain('opened={workbenchAddOpen}')
    expect(shellSource).toContain('onChange={setWorkbenchAddOpen}')
    expect(shellSource).toContain('data-workbench-tab={tool.id}')
    expect(shellSource).toContain('data-workbench-close={tool.id}')
    expect(shellSource).toContain("case 'dsh-work/browser':")
    expect(shellSource).toContain('workbenchTabs.opened.map((tab) =>')
    expect(shellSource).toContain('onClick={() => activateWorkbenchTab(tool.id)}')
    expect(shellSource).toContain('onClick={() => closeWorkbenchTab(tool.id)}')
    expect(shellSource).toContain('aria-controls={`workbench-panel-${tool.id}`}')
    expect(shellSource).not.toContain('setRightTab(')
    expect(shellSource).toContain('<BrowserWorkspace')
    expect(shellSource).toContain('active={rightTab === tool.id && workbenchNativeViewActive}')
    expect(browserSource).toContain('data-browser-workspace')
    expect(browserSource).toContain('browserWorkspaceCreateTab')
    expect(browserSource).toContain('browserWorkspaceGoBack')
    expect(browserSource).toContain('browserWorkspaceReload')
    expect(browserSource).toContain('browserWorkspaceSetVisible?.(active)')
    expect(browserSource).toContain('if (!active || !supported) return')
  })

  it('shows permission decisions and only adds a page to the conversation draft', () => {
    expect(browserSource).toContain('本次允许')
    expect(browserSource).toContain('始终允许')
    expect(browserSource).toContain('站点权限')
    expect(browserSource).toContain('加入对话')
    expect(shellSource).toContain('requestedBrowserPage={requestedBrowserPage}')
    expect(shellSource).not.toContain('dispatchBrowserPage')
  })

  it('exposes real browser controls through the bounded desktop bridge', () => {
    expect(browserSource).toContain('data-browser-menu-trigger')
    expect(browserSource).toContain('在页面中查找')
    expect(browserSource).toContain('截取屏幕截图')
    expect(browserSource).toContain('清除浏览数据')
    expect(browserSource).toContain('历史记录')
    expect(browserSource).toContain('data-browser-history')
    expect(browserSource).toContain('data-browser-downloads')
    expect(browserSource).toContain('data-browser-settings')
    expect(browserSource).toContain('browserWorkspaceSetZoom')
    expect(browserSource).toContain('browserWorkspaceSaveScreenshot')
    expect(browserSource).toContain('browserWorkspaceClearData')
    expect(browserSource).toContain('browserWorkspaceRemoveHistory')
    expect(browserSource).toContain('browserWorkspaceClearHistory')
  })

  it('merges captured pages into the draft without sending a turn', () => {
    expect(shellSource).toContain('savePastedTextAttachment')
    expect(shellSource).toContain('网页已加入对话草稿，确认后再发送')
    const effectStart = conversationSource.indexOf('if (!requestedBrowserPage || consumedBrowserPageRef.current')
    const effectEnd = conversationSource.indexOf('}, [onRequestedBrowserPageConsumed, requestedBrowserPage])', effectStart)
    const draftEffect = conversationSource.slice(effectStart, effectEnd)
    expect(effectStart).toBeGreaterThan(0)
    expect(effectEnd).toBeGreaterThan(effectStart)
    expect(draftEffect).toContain('setInput')
    expect(draftEffect).toContain('setAttachments')
    expect(draftEffect).not.toContain('dispatch(')
    expect(draftEffect).not.toContain('startAgentTurn')
  })
})
